<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('ad_events', function (Blueprint $table) {
            $table->id();

            /*
             * Unique identifier for this individual event.
             *
             * Allows client/server retries to be de-duplicated
             * safely when event tracking is connected later.
             */
            $table->uuid('event_uuid')->unique();

            /*
             * Groups related events belonging to the same
             * advertising opportunity:
             *
             * decision -> impression -> click -> close/skip
             */
            $table->uuid('opportunity_uuid')
                ->nullable()
                ->index();

            /*
             * Video is nullable because some ad placements,
             * such as catalog banners or native ads, may not
             * belong to a specific video.
             */
            $table->foreignId('video_id')
                ->nullable()
                ->constrained('videos')
                ->nullOnDelete();

            /*
             * Snapshot of the provider slug at event time.
             *
             * Examples:
             * xvideos
             * future-provider
             */
            $table->string('provider_slug', 100)
                ->nullable()
                ->index();

            /*
             * Advertising format.
             *
             * Examples:
             * native
             * banner
             * preroll
             * midroll
             * popunder
             * interstitial
             */
            $table->string('format', 32)
                ->index();

            /*
             * Event type.
             *
             * Examples:
             * decision
             * impression
             * click
             * skip
             * close
             * error
             */
            $table->string('event_type', 32)
                ->index();

            /*
             * Used primarily when event_type = decision.
             *
             * Examples:
             * show
             * skip
             */
            $table->string('decision_outcome', 16)
                ->nullable()
                ->index();

            /*
             * Decision engine reason.
             *
             * Examples:
             * eligible
             * provider_has_own_ads
             * master_disabled
             * frequency_cap
             * session_limit
             * interruption_budget_exhausted
             */
            $table->string('decision_reason', 100)
                ->nullable()
                ->index();

            /*
             * Logical placement inside Xurvexa.
             *
             * Examples:
             * home_grid
             * category_grid
             * video_player
             * video_sidebar
             */
            $table->string('placement_key', 100)
                ->nullable()
                ->index();

            /*
             * External advertising network information.
             * These remain nullable until ad networks are
             * integrated.
             */
            $table->string('ad_network', 100)
                ->nullable()
                ->index();

            $table->string('campaign_key', 100)
                ->nullable()
                ->index();

            /*
             * Future A/B testing support.
             */
            $table->string('experiment_key', 100)
                ->nullable()
                ->index();

            $table->string('experiment_variant', 50)
                ->nullable();

            /*
             * Random session identifier generated by Xurvexa.
             *
             * This is intentionally session-scoped rather than
             * storing a raw IP address or persistent fingerprint.
             */
            $table->string('session_key', 64)
                ->nullable()
                ->index();

            /*
             * Examples:
             * desktop
             * mobile
             * tablet
             * unknown
             */
            $table->string('device_type', 16)
                ->nullable()
                ->index();

            /*
             * Number of units consumed from the shared
             * interruption budget by this event.
             *
             * Usually:
             * 0 = non-disruptive
             * 1 = disruptive impression
             */
            $table->unsignedSmallInteger('interruption_cost')
                ->default(0);

            /*
             * Estimated or confirmed revenue represented in
             * micros to avoid floating-point accounting errors.
             *
             * Example:
             * 1 USD = 1,000,000 micros
             */
            $table->bigInteger('revenue_micros')
                ->nullable();

            $table->char('currency', 3)
                ->nullable();

            /*
             * Extensible provider/network metadata.
             *
             * Keep sensitive personal data out of this field.
             */
            $table->json('metadata')
                ->nullable();

            /*
             * Actual event occurrence time.
             *
             * created_at remains the database ingestion time.
             */
            $table->timestampTz('occurred_at')
                ->index();

            $table->timestamps();

            /*
             * Analytics-oriented composite indexes.
             */
            $table->index(
                [
                    'format',
                    'event_type',
                    'occurred_at',
                ],
                'ad_events_format_type_time_idx'
            );

            $table->index(
                [
                    'provider_slug',
                    'event_type',
                    'occurred_at',
                ],
                'ad_events_provider_type_time_idx'
            );

            $table->index(
                [
                    'video_id',
                    'event_type',
                    'occurred_at',
                ],
                'ad_events_video_type_time_idx'
            );
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ad_events');
    }
};
